[2022-11-14 15:48:03,446] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-11-14 15:48:03,468] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-11-14 15:48:03,469] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:48:03,469] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:48:03,469] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:48:03,486] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-08-02 06:00:00+00:00
[2022-11-14 15:48:03,495] {standard_task_runner.py:52} INFO - Started process 629 to run task
[2022-11-14 15:48:03,503] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-08-02T06:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpta6j1w41', '--error-file', '/tmp/tmpzmg8of8k']
[2022-11-14 15:48:03,504] {standard_task_runner.py:77} INFO - Job 166: Subtask download_dataset_task
[2022-11-14 15:48:03,589] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-08-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:48:03,657] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:48:03,684] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-02T06:00:00+00:00
[2022-11-14 15:48:03,686] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:48:03,687] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip+data/yellow_tripdata_2019-08.parquet > /opt/***/yellow_tripdata_2019-08.parquet']
[2022-11-14 15:48:03,708] {subprocess.py:85} INFO - Output:
[2022-11-14 15:48:04,068] {subprocess.py:89} INFO - curl: (22) The requested URL returned error: 403
[2022-11-14 15:48:04,069] {subprocess.py:93} INFO - Command exited with return code 22
[2022-11-14 15:48:04,087] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:48:04,096] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190802T060000, start_date=20221114T154803, end_date=20221114T154804
[2022-11-14 15:48:04,114] {standard_task_runner.py:92} ERROR - Failed to execute job 166 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:48:04,162] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-14 15:48:04,209] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-14 15:53:50,909] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-11-14 15:53:50,935] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-11-14 15:53:50,936] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:53:50,936] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:53:50,936] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:53:50,956] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-08-02 06:00:00+00:00
[2022-11-14 15:53:50,965] {standard_task_runner.py:52} INFO - Started process 954 to run task
[2022-11-14 15:53:50,973] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-08-02T06:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpjjarfb3k', '--error-file', '/tmp/tmpr2yu06ri']
[2022-11-14 15:53:50,975] {standard_task_runner.py:77} INFO - Job 187: Subtask download_dataset_task
[2022-11-14 15:53:51,080] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-08-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:53:51,146] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:53:51,204] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-02T06:00:00+00:00
[2022-11-14 15:53:51,207] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:53:51,209] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-08.parquet > /opt/***/yellow_tripdata_2019-08.parquet']
[2022-11-14 15:53:51,271] {subprocess.py:85} INFO - Output:
[2022-11-14 15:53:52,995] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-14 15:53:53,272] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190802T060000, start_date=20221114T155350, end_date=20221114T155353
[2022-11-14 15:53:53,324] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-14 15:53:53,418] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
