[2022-11-14 15:37:12,101] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-11-14 15:37:12,133] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-11-14 15:37:12,134] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:37:12,134] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:37:12,134] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:37:12,180] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-02-02 06:00:00+00:00
[2022-11-14 15:37:12,192] {standard_task_runner.py:52} INFO - Started process 121 to run task
[2022-11-14 15:37:12,215] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-02-02T06:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmp8magzidp', '--error-file', '/tmp/tmp0ozbk8fp']
[2022-11-14 15:37:12,227] {standard_task_runner.py:77} INFO - Job 155: Subtask download_dataset_task
[2022-11-14 15:37:12,431] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:37:12,563] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:37:12,663] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T06:00:00+00:00
[2022-11-14 15:37:12,670] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:37:12,672] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip+data/yellow_tripdata_2019-02.parquet > /opt/***/yellow_tripdata_2019-02.parquet']
[2022-11-14 15:37:12,693] {subprocess.py:85} INFO - Output:
[2022-11-14 15:37:13,144] {subprocess.py:89} INFO - curl: (22) The requested URL returned error: 403
[2022-11-14 15:37:13,146] {subprocess.py:93} INFO - Command exited with return code 22
[2022-11-14 15:37:13,188] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:37:13,201] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190202T060000, start_date=20221114T153712, end_date=20221114T153713
[2022-11-14 15:37:13,228] {standard_task_runner.py:92} ERROR - Failed to execute job 155 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:37:13,281] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-14 15:37:13,367] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-14 15:52:42,144] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-11-14 15:52:42,165] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-11-14 15:52:42,165] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:52:42,165] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:52:42,166] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:52:42,182] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-02-02 06:00:00+00:00
[2022-11-14 15:52:42,190] {standard_task_runner.py:52} INFO - Started process 834 to run task
[2022-11-14 15:52:42,198] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-02-02T06:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmp4fwllivr', '--error-file', '/tmp/tmpp4jr80uq']
[2022-11-14 15:52:42,199] {standard_task_runner.py:77} INFO - Job 169: Subtask download_dataset_task
[2022-11-14 15:52:42,319] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:52:42,414] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:52:42,446] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T06:00:00+00:00
[2022-11-14 15:52:42,447] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:52:42,448] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-02.parquet > /opt/***/yellow_tripdata_2019-02.parquet']
[2022-11-14 15:52:42,471] {subprocess.py:85} INFO - Output:
[2022-11-14 15:52:43,764] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-14 15:52:43,929] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190202T060000, start_date=20221114T155242, end_date=20221114T155243
[2022-11-14 15:52:44,101] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-14 15:52:44,297] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-16 09:20:57,682] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-11-16 09:20:57,697] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-11-16 09:20:57,698] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:20:57,698] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-16 09:20:57,698] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:20:57,716] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-02-02 06:00:00+00:00
[2022-11-16 09:20:57,724] {standard_task_runner.py:52} INFO - Started process 185 to run task
[2022-11-16 09:20:57,735] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-02-02T06:00:00+00:00', '--job-id', '705', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpp3pmh0ty', '--error-file', '/tmp/tmporizbyf3']
[2022-11-16 09:20:57,738] {standard_task_runner.py:77} INFO - Job 705: Subtask download_dataset_task
[2022-11-16 09:20:57,830] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-02-02T06:00:00+00:00 [running]> on host 75ceca4d9264
[2022-11-16 09:20:57,886] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-16 09:20:57,916] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T06:00:00+00:00
[2022-11-16 09:20:57,918] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-16 09:20:57,919] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-02.parquet > /opt/***/yellow_tripdata_2019-02.parquet']
[2022-11-16 09:20:57,941] {subprocess.py:85} INFO - Output:
[2022-11-16 09:20:59,272] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-16 09:20:59,322] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190202T060000, start_date=20221116T092057, end_date=20221116T092059
[2022-11-16 09:20:59,358] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-16 09:20:59,429] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
