[2022-11-14 15:37:12,056] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-11-14 15:37:12,105] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-11-14 15:37:12,106] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:37:12,106] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:37:12,106] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:37:12,140] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-11-14 15:37:12,149] {standard_task_runner.py:52} INFO - Started process 119 to run task
[2022-11-14 15:37:12,171] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpgmt0rliz', '--error-file', '/tmp/tmp6gxspkh0']
[2022-11-14 15:37:12,173] {standard_task_runner.py:77} INFO - Job 153: Subtask download_dataset_task
[2022-11-14 15:37:12,388] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:37:12,533] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:37:12,656] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-11-14 15:37:12,661] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:37:12,662] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip+data/yellow_tripdata_2019-01.parquet > /opt/***/yellow_tripdata_2019-01.parquet']
[2022-11-14 15:37:12,692] {subprocess.py:85} INFO - Output:
[2022-11-14 15:37:13,150] {subprocess.py:89} INFO - curl: (22) The requested URL returned error: 403
[2022-11-14 15:37:13,153] {subprocess.py:93} INFO - Command exited with return code 22
[2022-11-14 15:37:13,189] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:37:13,203] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20221114T153712, end_date=20221114T153713
[2022-11-14 15:37:13,235] {standard_task_runner.py:92} ERROR - Failed to execute job 153 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:37:13,268] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-14 15:37:13,334] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-14 15:52:41,743] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-11-14 15:52:41,766] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-11-14 15:52:41,766] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:52:41,767] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:52:41,767] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:52:41,790] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-11-14 15:52:41,800] {standard_task_runner.py:52} INFO - Started process 830 to run task
[2022-11-14 15:52:41,816] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmp_bg42el5', '--error-file', '/tmp/tmpsgkb29v_']
[2022-11-14 15:52:41,819] {standard_task_runner.py:77} INFO - Job 168: Subtask download_dataset_task
[2022-11-14 15:52:41,927] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:52:42,003] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:52:42,050] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-11-14 15:52:42,052] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:52:42,055] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-01.parquet > /opt/***/yellow_tripdata_2019-01.parquet']
[2022-11-14 15:52:42,078] {subprocess.py:85} INFO - Output:
[2022-11-14 15:52:42,952] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-14 15:52:43,140] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20221114T155241, end_date=20221114T155243
[2022-11-14 15:52:43,199] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-14 15:52:43,312] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-11-16 09:20:57,369] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-11-16 09:20:57,394] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-11-16 09:20:57,394] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:20:57,395] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-16 09:20:57,395] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:20:57,423] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 06:00:00+00:00
[2022-11-16 09:20:57,453] {standard_task_runner.py:52} INFO - Started process 182 to run task
[2022-11-16 09:20:57,465] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '704', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmprz9ee3jd', '--error-file', '/tmp/tmp3b8kaau6']
[2022-11-16 09:20:57,468] {standard_task_runner.py:77} INFO - Job 704: Subtask download_dataset_task
[2022-11-16 09:20:57,571] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host 75ceca4d9264
[2022-11-16 09:20:57,637] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-16 09:20:57,674] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-11-16 09:20:57,676] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-16 09:20:57,677] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-01.parquet > /opt/***/yellow_tripdata_2019-01.parquet']
[2022-11-16 09:20:57,704] {subprocess.py:85} INFO - Output:
[2022-11-16 09:20:58,725] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-16 09:20:58,769] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190102T060000, start_date=20221116T092057, end_date=20221116T092058
[2022-11-16 09:20:58,833] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-16 09:20:58,899] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
