[2022-11-14 15:37:12,048] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-11-14 15:37:12,094] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-11-14 15:37:12,094] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:37:12,095] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:37:12,095] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:37:12,138] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-03-02 06:00:00+00:00
[2022-11-14 15:37:12,150] {standard_task_runner.py:52} INFO - Started process 120 to run task
[2022-11-14 15:37:12,170] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmp0il5q8mt', '--error-file', '/tmp/tmppze1s1e8']
[2022-11-14 15:37:12,172] {standard_task_runner.py:77} INFO - Job 154: Subtask download_dataset_task
[2022-11-14 15:37:12,340] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:37:12,503] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:37:12,580] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-11-14 15:37:12,582] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:37:12,583] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip+data/yellow_tripdata_2019-03.parquet > /opt/***/yellow_tripdata_2019-03.parquet']
[2022-11-14 15:37:12,619] {subprocess.py:85} INFO - Output:
[2022-11-14 15:37:13,126] {subprocess.py:89} INFO - curl: (22) The requested URL returned error: 403
[2022-11-14 15:37:13,128] {subprocess.py:93} INFO - Command exited with return code 22
[2022-11-14 15:37:13,157] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:37:13,176] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190302T060000, start_date=20221114T153712, end_date=20221114T153713
[2022-11-14 15:37:13,209] {standard_task_runner.py:92} ERROR - Failed to execute job 154 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:37:13,263] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-14 15:37:13,337] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-14 15:52:42,417] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-11-14 15:52:42,446] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-11-14 15:52:42,446] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:52:42,446] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:52:42,446] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:52:42,476] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-03-02 06:00:00+00:00
[2022-11-14 15:52:42,490] {standard_task_runner.py:52} INFO - Started process 838 to run task
[2022-11-14 15:52:42,496] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpt1fkjxvg', '--error-file', '/tmp/tmpmwpibuon']
[2022-11-14 15:52:42,498] {standard_task_runner.py:77} INFO - Job 170: Subtask download_dataset_task
[2022-11-14 15:52:42,593] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:52:42,667] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:52:42,806] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-11-14 15:52:42,807] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:52:42,808] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-03.parquet > /opt/***/yellow_tripdata_2019-03.parquet']
[2022-11-14 15:52:42,825] {subprocess.py:85} INFO - Output:
[2022-11-14 15:52:44,459] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-14 15:52:44,526] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190302T060000, start_date=20221114T155242, end_date=20221114T155244
[2022-11-14 15:52:44,613] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-14 15:52:44,759] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-11-16 09:20:57,917] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-11-16 09:20:57,932] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-11-16 09:20:57,933] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:20:57,933] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-16 09:20:57,933] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:20:57,957] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-03-02 06:00:00+00:00
[2022-11-16 09:20:57,966] {standard_task_runner.py:52} INFO - Started process 190 to run task
[2022-11-16 09:20:57,981] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '706', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpob9iepiv', '--error-file', '/tmp/tmp5ji7n3om']
[2022-11-16 09:20:57,983] {standard_task_runner.py:77} INFO - Job 706: Subtask download_dataset_task
[2022-11-16 09:20:58,094] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host 75ceca4d9264
[2022-11-16 09:20:58,154] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-16 09:20:58,188] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-11-16 09:20:58,190] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-16 09:20:58,191] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-03.parquet > /opt/***/yellow_tripdata_2019-03.parquet']
[2022-11-16 09:20:58,209] {subprocess.py:85} INFO - Output:
[2022-11-16 09:21:01,525] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-16 09:21:01,592] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190302T060000, start_date=20221116T092057, end_date=20221116T092101
[2022-11-16 09:21:01,662] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-16 09:21:01,740] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
