[2022-11-14 15:42:49,410] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2022-11-14 15:42:49,423] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2022-11-14 15:42:49,423] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:42:49,423] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:42:49,423] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:42:49,438] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-05-02 06:00:00+00:00
[2022-11-14 15:42:49,446] {standard_task_runner.py:52} INFO - Started process 384 to run task
[2022-11-14 15:42:49,454] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-05-02T06:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmp3r7lne_b', '--error-file', '/tmp/tmpri7u6dfq']
[2022-11-14 15:42:49,455] {standard_task_runner.py:77} INFO - Job 160: Subtask download_dataset_task
[2022-11-14 15:42:49,544] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:42:49,595] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:42:49,631] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-05-02T06:00:00+00:00
[2022-11-14 15:42:49,633] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:42:49,634] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip+data/yellow_tripdata_2019-05.parquet > /opt/***/yellow_tripdata_2019-05.parquet']
[2022-11-14 15:42:49,656] {subprocess.py:85} INFO - Output:
[2022-11-14 15:42:50,126] {subprocess.py:89} INFO - curl: (22) The requested URL returned error: 403
[2022-11-14 15:42:50,128] {subprocess.py:93} INFO - Command exited with return code 22
[2022-11-14 15:42:50,149] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:42:50,158] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190502T060000, start_date=20221114T154249, end_date=20221114T154250
[2022-11-14 15:42:50,177] {standard_task_runner.py:92} ERROR - Failed to execute job 160 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:42:50,202] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-14 15:42:50,249] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-14 15:53:18,755] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2022-11-14 15:53:18,774] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2022-11-14 15:53:18,774] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:53:18,774] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:53:18,775] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:53:18,802] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-05-02 06:00:00+00:00
[2022-11-14 15:53:18,826] {standard_task_runner.py:52} INFO - Started process 893 to run task
[2022-11-14 15:53:18,840] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-05-02T06:00:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpuasg91jo', '--error-file', '/tmp/tmpje94vr8p']
[2022-11-14 15:53:18,842] {standard_task_runner.py:77} INFO - Job 178: Subtask download_dataset_task
[2022-11-14 15:53:18,974] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:53:19,053] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:53:19,089] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-05-02T06:00:00+00:00
[2022-11-14 15:53:19,090] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:53:19,091] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-05.parquet > /opt/***/yellow_tripdata_2019-05.parquet']
[2022-11-14 15:53:19,115] {subprocess.py:85} INFO - Output:
[2022-11-14 15:53:21,702] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-14 15:53:21,826] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190502T060000, start_date=20221114T155318, end_date=20221114T155321
[2022-11-14 15:53:21,907] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-14 15:53:21,997] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-11-16 09:21:23,222] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2022-11-16 09:21:23,235] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2022-11-16 09:21:23,236] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:21:23,236] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-16 09:21:23,236] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:21:23,249] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-05-02 06:00:00+00:00
[2022-11-16 09:21:23,258] {standard_task_runner.py:52} INFO - Started process 257 to run task
[2022-11-16 09:21:23,265] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-05-02T06:00:00+00:00', '--job-id', '717', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpup3zu2iq', '--error-file', '/tmp/tmp1gtdc9dw']
[2022-11-16 09:21:23,267] {standard_task_runner.py:77} INFO - Job 717: Subtask download_dataset_task
[2022-11-16 09:21:23,345] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-05-02T06:00:00+00:00 [running]> on host 75ceca4d9264
[2022-11-16 09:21:23,394] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-16 09:21:23,419] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-05-02T06:00:00+00:00
[2022-11-16 09:21:23,421] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-16 09:21:23,422] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-05.parquet > /opt/***/yellow_tripdata_2019-05.parquet']
[2022-11-16 09:21:23,439] {subprocess.py:85} INFO - Output:
[2022-11-16 09:21:26,276] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-16 09:21:26,309] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190502T060000, start_date=20221116T092123, end_date=20221116T092126
[2022-11-16 09:21:26,373] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-16 09:21:26,420] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
