[2022-11-14 15:42:49,612] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-11-14 15:42:49,632] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-11-14 15:42:49,633] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:42:49,633] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:42:49,633] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:42:49,657] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-06-02 06:00:00+00:00
[2022-11-14 15:42:49,665] {standard_task_runner.py:52} INFO - Started process 387 to run task
[2022-11-14 15:42:49,679] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpxn6wewzr', '--error-file', '/tmp/tmplusv7sxf']
[2022-11-14 15:42:49,682] {standard_task_runner.py:77} INFO - Job 161: Subtask download_dataset_task
[2022-11-14 15:42:49,763] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:42:49,818] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:42:49,850] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-11-14 15:42:49,852] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:42:49,853] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip+data/yellow_tripdata_2019-06.parquet > /opt/***/yellow_tripdata_2019-06.parquet']
[2022-11-14 15:42:49,875] {subprocess.py:85} INFO - Output:
[2022-11-14 15:42:50,332] {subprocess.py:89} INFO - curl: (22) The requested URL returned error: 403
[2022-11-14 15:42:50,334] {subprocess.py:93} INFO - Command exited with return code 22
[2022-11-14 15:42:50,354] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:42:50,362] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190602T060000, start_date=20221114T154249, end_date=20221114T154250
[2022-11-14 15:42:50,379] {standard_task_runner.py:92} ERROR - Failed to execute job 161 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-14 15:42:50,420] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-14 15:42:50,465] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-14 15:53:19,202] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-11-14 15:53:19,229] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-11-14 15:53:19,229] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:53:19,229] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-14 15:53:19,230] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 15:53:19,253] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-06-02 06:00:00+00:00
[2022-11-14 15:53:19,262] {standard_task_runner.py:52} INFO - Started process 901 to run task
[2022-11-14 15:53:19,270] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpxfbhnxtk', '--error-file', '/tmp/tmpoqxg6f12']
[2022-11-14 15:53:19,272] {standard_task_runner.py:77} INFO - Job 179: Subtask download_dataset_task
[2022-11-14 15:53:19,362] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [running]> on host e030bae48f83
[2022-11-14 15:53:19,417] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-14 15:53:19,446] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-11-14 15:53:19,448] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-14 15:53:19,449] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-06.parquet > /opt/***/yellow_tripdata_2019-06.parquet']
[2022-11-14 15:53:19,466] {subprocess.py:85} INFO - Output:
[2022-11-14 15:53:21,386] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-14 15:53:21,561] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190602T060000, start_date=20221114T155319, end_date=20221114T155321
[2022-11-14 15:53:21,740] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-14 15:53:21,817] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-11-16 09:21:23,393] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-11-16 09:21:23,405] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-11-16 09:21:23,406] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:21:23,406] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-11-16 09:21:23,406] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 09:21:23,420] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-06-02 06:00:00+00:00
[2022-11-16 09:21:23,428] {standard_task_runner.py:52} INFO - Started process 258 to run task
[2022-11-16 09:21:23,436] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data_v2', 'download_dataset_task', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '718', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmp9z6j4x5q', '--error-file', '/tmp/tmp3t363xwf']
[2022-11-16 09:21:23,438] {standard_task_runner.py:77} INFO - Job 718: Subtask download_dataset_task
[2022-11-16 09:21:23,518] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data_v2.download_dataset_task scheduled__2019-06-02T06:00:00+00:00 [running]> on host 75ceca4d9264
[2022-11-16 09:21:23,568] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-16 09:21:23,593] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data_v2
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-11-16 09:21:23,595] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-16 09:21:23,596] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-06.parquet > /opt/***/yellow_tripdata_2019-06.parquet']
[2022-11-16 09:21:23,615] {subprocess.py:85} INFO - Output:
[2022-11-16 09:21:26,795] {subprocess.py:93} INFO - Command exited with return code 0
[2022-11-16 09:21:26,875] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_data_v2, task_id=download_dataset_task, execution_date=20190602T060000, start_date=20221116T092123, end_date=20221116T092126
[2022-11-16 09:21:26,959] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-16 09:21:27,077] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
